### Data recibida del Senamhi por solicitud oficial 

Pre procesamiento de los datos metereologicos por región
(cambio en la estructura)

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('huarmey.csv')
df

,V Cod Para,V Año,V Dia,Periodo,1,2,3,4,5,6,7,8,9,10,11,12
0,PT101,2015,1,'15-01,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
1,PT101,2015,2,'15-02,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
2,PT101,2015,3,'15-03,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
3,PT101,2015,4,'15-04,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
4,PT101,2015,5,'15-05,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
5,PT101,2015,6,'15-06,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
6,PT101,2015,7,'15-07,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
7,PT101,2015,8,'15-08,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
8,PT101,2015,9,'15-09,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
9,PT101,2015,10,'15-10,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
10,PT101,2015,11,'15-11,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
11,PT101,2015,12,'15-12,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
12,PT101,2015,13,'15-13,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
13,PT101,2015,14,'15-14,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
14,PT101,2015,15,'15-15,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,-888
15,PT101,2015,16,'15-16,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,-888
16,PT101,2015,17,'15-17,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
17,PT101,2015,18,'15-18,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
18,PT101,2015,19,'15-19,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
19,PT101,2015,20,'15-20,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
20,PT101,2015,21,'15-21,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
21,PT101,2015,22,'15-22,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
22,PT101,2015,23,'15-23,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
23,PT101,2015,24,'15-24,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
24,PT101,2015,25,'15-25,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
25,PT101,2015,26,'15-26,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
26,PT101,2015,27,'15-27,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,2.2,0,0
27,PT101,2015,28,'15-28,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
28,PT101,2015,29,'15-29,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
29,PT101,2015,30,'15-30,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,VT107,2017,2,'17-02,8,2,S/D,S/D,S/D,2.7,0.7,S/D,S/D,S/D,S/D,S/D
228,VT107,2017,3,'17-03,8,4,2.7,4.7,4.3,4,5.3,S/D,5.3,S/D,S/D,S/D
229,VT107,2017,4,'17-04,5.3,S/D,2.7,4,S/D,S/D,2,3.3,S/D,S/D,S/D,S/D
230,VT107,2017,5,'17-05,2.7,4.7,2.7,2.7,3.3,4,S/D,2.7,3.3,S/D,S/D,S/D
231,VT107,2017,6,'17-06,4,7,4,2.3,4,4.7,2,4,S/D,S/D,S/D,S/D
232,VT107,2017,7,'17-07,5,4.7,4,2.7,5.7,5,4,S/D,S/D,S/D,S/D,S/D
233,VT107,2017,8,'17-08,2.7,2.7,2.7,2.7,4.3,3.7,S/D,S/D,S/D,S/D,S/D,S/D
234,VT107,2017,9,'17-09,3.3,4,4,2,S/D,4.3,2,2.7,S/D,S/D,S/D,S/D
235,VT107,2017,10,'17-10,S/D,5.3,2,3,2,5.3,3.3,3.3,S/D,S/D,S/D,S/D
236,VT107,2017,11,'17-11,S/D,4.3,2.7,6.3,4,2,1.3,6,S/D,S/D,S/D,S/D
237,VT107,2017,12,'17-12,4,S/D,1.3,5.3,S/D,2,2,5.7,7,S/D,S/D,S/D
238,VT107,2017,13,'17-13,2.7,S/D,2,4.7,3.3,2,2.7,9,7.3,S/D,S/D,S/D
239,VT107,2017,14,'17-14,4.7,0.7,1.3,S/D,S/D,2.7,S/D,7,S/D,S/D,S/D,S/D
240,VT107,2017,15,'17-15,2,2.7,1.3,7,4.7,3.3,3.3,S/D,S/D,S/D,S/D,S/D
241,VT107,2017,16,'17-16,2,2.7,0.7,3.3,S/D,S/D,4.7,3.3,5.3,S/D,S/D,S/D
242,VT107,2017,17,'17-17,2,S/D,2,4,7.7,S/D,4,S/D,4,S/D,S/D,S/D
243,VT107,2017,18,'17-18,6.3,4,2,4,S/D,S/D,3.3,4.7,S/D,S/D,S/D,S/D
244,VT107,2017,19,'17-19,S/D,3.3,S/D,6.3,2.7,S/D,1.3,S/D,S/D,S/D,S/D,S/D
245,VT107,2017,20,'17-20,2.7,3.7,S/D,5.3,4.3,2.7,S/D,3.3,S/D,S/D,S/D,S/D
246,VT107,2017,21,'17-21,2,1.3,2.7,3.3,S/D,3.3,2.7,S/D,S/D,S/D,S/D,S/D
247,VT107,2017,22,'17-22,2.7,2,2.7,5.7,3.3,S/D,3.3,4.7,S/D,S/D,S/D,S/D
248,VT107,2017,23,'17-23,7.7,2.7,S/D,6,3.3,2,S/D,4.7,4.7,S/D,S/D,S/D
249,VT107,2017,24,'17-24,S/D,3.3,2.7,S/D,4.7,2,S/D,2,4.7,S/D,S/D,S/D
250,VT107,2017,25,'17-25,3.3,2,S/D,7,2.7,3.3,2.7,S/D,4.7,S/D,S/D,S/D
251,VT107,2017,26,'17-26,3.3,2.7,2,4.7,3.3,S/D,S/D,S/D,4,S/D,S/D,S/D
252,VT107,2017,27,'17-27,2.7,4,1.3,7.3,3.3,S/D,3.3,S/D,S/D,S/D,S/D,S/D
253,VT107,2017,28,'17-28,3.3,4.7,S/D,4.7,4.7,4.7,S/D,4,S/D,S/D,S/D,S/D
254,VT107,2017,29,'17-29,3.3,S/D,S/D,4.7,S/D,S/D,2,5.3,6.3,S/D,S/D,S/D
255,VT107,2017,30,'17-30,4,S/D,S/D,5.3,S/D,4,2,4.7,S/D,S/D,S/D,S/D
256,VT107,2017,31,'17-31,4.7,S/D,4,S/D,3.3,S/D,S/D,5.3,S/D,S/D,S/D,S/D

In [3]:
#Parameter PT101 (precipitaciones)
pt = df[df['V Cod Para'] == 'PT101']

In [4]:
#Parameter TM101 
tm = df[df['V Cod Para'] == 'TM101']

In [5]:
#Parameter VT107 
vt = df[df['V Cod Para'] == 'VT107']

In [6]:
vt

,V Cod Para,V Año,V Dia,Periodo,1,2,3,4,5,6,7,8,9,10,11,12
186,VT107,2015,3,'15-03,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,2
187,VT107,2015,4,'15-04,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,2
188,VT107,2015,5,'15-05,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4
189,VT107,2015,7,'15-07,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4
190,VT107,2015,9,'15-09,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,3.3
191,VT107,2015,10,'15-10,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4
192,VT107,2015,11,'15-11,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4
193,VT107,2015,12,'15-12,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4.3
194,VT107,2015,14,'15-14,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4
195,VT107,2015,15,'15-15,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,3.3
196,VT107,2015,16,'15-16,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,5.7
197,VT107,2015,23,'15-23,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,6
198,VT107,2015,24,'15-24,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4.7
199,VT107,2015,25,'15-25,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4.3
200,VT107,2015,26,'15-26,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4.7
201,VT107,2015,27,'15-27,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,2.7
202,VT107,2015,28,'15-28,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,3.3
203,VT107,2016,1,'16-01,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,3.3
204,VT107,2016,2,'16-02,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4
205,VT107,2016,4,'16-04,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,5.3
206,VT107,2016,5,'16-05,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,2
207,VT107,2016,8,'16-08,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,4.7
208,VT107,2016,9,'16-09,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,5.7
209,VT107,2016,11,'16-11,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,7
210,VT107,2016,12,'16-12,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,7.7
211,VT107,2016,13,'16-13,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,3.3
212,VT107,2016,16,'16-16,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,6.3
213,VT107,2016,17,'16-17,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,6.3
214,VT107,2016,18,'16-18,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,5.7
215,VT107,2016,19,'16-19,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,S/D,6.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,VT107,2017,2,'17-02,8,2,S/D,S/D,S/D,2.7,0.7,S/D,S/D,S/D,S/D,S/D
228,VT107,2017,3,'17-03,8,4,2.7,4.7,4.3,4,5.3,S/D,5.3,S/D,S/D,S/D
229,VT107,2017,4,'17-04,5.3,S/D,2.7,4,S/D,S/D,2,3.3,S/D,S/D,S/D,S/D
230,VT107,2017,5,'17-05,2.7,4.7,2.7,2.7,3.3,4,S/D,2.7,3.3,S/D,S/D,S/D
231,VT107,2017,6,'17-06,4,7,4,2.3,4,4.7,2,4,S/D,S/D,S/D,S/D
232,VT107,2017,7,'17-07,5,4.7,4,2.7,5.7,5,4,S/D,S/D,S/D,S/D,S/D
233,VT107,2017,8,'17-08,2.7,2.7,2.7,2.7,4.3,3.7,S/D,S/D,S/D,S/D,S/D,S/D
234,VT107,2017,9,'17-09,3.3,4,4,2,S/D,4.3,2,2.7,S/D,S/D,S/D,S/D
235,VT107,2017,10,'17-10,S/D,5.3,2,3,2,5.3,3.3,3.3,S/D,S/D,S/D,S/D
236,VT107,2017,11,'17-11,S/D,4.3,2.7,6.3,4,2,1.3,6,S/D,S/D,S/D,S/D
237,VT107,2017,12,'17-12,4,S/D,1.3,5.3,S/D,2,2,5.7,7,S/D,S/D,S/D
238,VT107,2017,13,'17-13,2.7,S/D,2,4.7,3.3,2,2.7,9,7.3,S/D,S/D,S/D
239,VT107,2017,14,'17-14,4.7,0.7,1.3,S/D,S/D,2.7,S/D,7,S/D,S/D,S/D,S/D
240,VT107,2017,15,'17-15,2,2.7,1.3,7,4.7,3.3,3.3,S/D,S/D,S/D,S/D,S/D
241,VT107,2017,16,'17-16,2,2.7,0.7,3.3,S/D,S/D,4.7,3.3,5.3,S/D,S/D,S/D
242,VT107,2017,17,'17-17,2,S/D,2,4,7.7,S/D,4,S/D,4,S/D,S/D,S/D
243,VT107,2017,18,'17-18,6.3,4,2,4,S/D,S/D,3.3,4.7,S/D,S/D,S/D,S/D
244,VT107,2017,19,'17-19,S/D,3.3,S/D,6.3,2.7,S/D,1.3,S/D,S/D,S/D,S/D,S/D
245,VT107,2017,20,'17-20,2.7,3.7,S/D,5.3,4.3,2.7,S/D,3.3,S/D,S/D,S/D,S/D
246,VT107,2017,21,'17-21,2,1.3,2.7,3.3,S/D,3.3,2.7,S/D,S/D,S/D,S/D,S/D
247,VT107,2017,22,'17-22,2.7,2,2.7,5.7,3.3,S/D,3.3,4.7,S/D,S/D,S/D,S/D
248,VT107,2017,23,'17-23,7.7,2.7,S/D,6,3.3,2,S/D,4.7,4.7,S/D,S/D,S/D
249,VT107,2017,24,'17-24,S/D,3.3,2.7,S/D,4.7,2,S/D,2,4.7,S/D,S/D,S/D
250,VT107,2017,25,'17-25,3.3,2,S/D,7,2.7,3.3,2.7,S/D,4.7,S/D,S/D,S/D
251,VT107,2017,26,'17-26,3.3,2.7,2,4.7,3.3,S/D,S/D,S/D,4,S/D,S/D,S/D
252,VT107,2017,27,'17-27,2.7,4,1.3,7.3,3.3,S/D,3.3,S/D,S/D,S/D,S/D,S/D
253,VT107,2017,28,'17-28,3.3,4.7,S/D,4.7,4.7,4.7,S/D,4,S/D,S/D,S/D,S/D
254,VT107,2017,29,'17-29,3.3,S/D,S/D,4.7,S/D,S/D,2,5.3,6.3,S/D,S/D,S/D
255,VT107,2017,30,'17-30,4,S/D,S/D,5.3,S/D,4,2,4.7,S/D,S/D,S/D,S/D
256,VT107,2017,31,'17-31,4.7,S/D,4,S/D,3.3,S/D,S/D,5.3,S/D,S/D,S/D,S/D

In [7]:
#Changes data structure 

def cambio_datestamp(df): 
    '''Cambia los valores de meses en los indices por valores en serie indexados por año, mes y dia'''
    values_array = np.array([['year', 'month', 'day', 'value']])
    for year in range(2015,2018):
        year_df = df[df['V Año'] == year]
        for month in range(1,13):
            month_df = year_df[str(month)]
            for day in range(0,31):
                day_value = month_df.iloc[day]
                fila = np.array([[year, month, day+1, day_value]])
                values_array = np.concatenate((values_array, fila), axis=0)

    return pd.DataFrame(values_array[1:-1], columns=values_array[0,:])

In [8]:
pt = cambio_datestamp(pt)

In [9]:
tm = cambio_datestamp(tm)

In [10]:
tm

      year month day value
0     2015     1   1   S/D
1     2015     1   2   S/D
2     2015     1   3   S/D
3     2015     1   4   S/D
4     2015     1   5   S/D
5     2015     1   6   S/D
6     2015     1   7   S/D
7     2015     1   8   S/D
8     2015     1   9   S/D
9     2015     1  10   S/D
10    2015     1  11   S/D
11    2015     1  12   S/D
12    2015     1  13   S/D
13    2015     1  14   S/D
14    2015     1  15   S/D
15    2015     1  16   S/D
16    2015     1  17   S/D
17    2015     1  18   S/D
18    2015     1  19   S/D
19    2015     1  20   S/D
20    2015     1  21   S/D
21    2015     1  22   S/D
22    2015     1  23   S/D
23    2015     1  24   S/D
24    2015     1  25   S/D
25    2015     1  26   S/D
26    2015     1  27   S/D
27    2015     1  28   S/D
28    2015     1  29   S/D
29    2015     1  30   S/D
...    ...   ...  ..   ...
1085  2017    12   1   S/D
1086  2017    12   2   S/D
1087  2017    12   3   S/D
1088  2017    12   4   S/D
1089  2017    12   5   S/D
1090  2017    12   6   S/D
1091  2017    12   7   S/D
1092  2017    12   8   S/D
1093  2017    12   9   S/D
1094  2017    12  10   S/D
1095  2017    12  11   S/D
1096  2017    12  12   S/D
1097  2017    12  13   S/D
1098  2017    12  14   S/D
1099  2017    12  15   S/D
1100  2017    12  16   S/D
1101  2017    12  17   S/D
1102  2017    12  18   S/D
1103  2017    12  19   S/D
1104  2017    12  20   S/D
1105  2017    12  21   S/D
1106  2017    12  22   S/D
1107  2017    12  23   S/D
1108  2017    12  24   S/D
1109  2017    12  25   S/D
1110  2017    12  26   S/D
1111  2017    12  27   S/D
1112  2017    12  28   S/D
1113  2017    12  29   S/D
1114  2017    12  30   S/D

[1115 rows x 4 columns]

In [12]:
#Reformat data 

def datestamp(df):
    df.year = df.year.astype(str).astype(int)
    df.month = df.month.astype(str).astype(int)
    df.day = df.day.astype(str).astype(int)
    df['date']=pd.to_datetime((df.year*10000 + df.month*100+df.day).apply(str),format='%Y%m%d',errors='coerce')
    df=df.drop(df[df.date.isnull()].index)
    df.value.replace('S/D', np.nan, regex=True, inplace = True)
    return df

In [13]:
pt = datestamp(pt)

In [14]:
tm = datestamp(tm)

In [15]:
tm

      year  month  day value       date
0     2015      1    1   NaN 2015-01-01
1     2015      1    2   NaN 2015-01-02
2     2015      1    3   NaN 2015-01-03
3     2015      1    4   NaN 2015-01-04
4     2015      1    5   NaN 2015-01-05
5     2015      1    6   NaN 2015-01-06
6     2015      1    7   NaN 2015-01-07
7     2015      1    8   NaN 2015-01-08
8     2015      1    9   NaN 2015-01-09
9     2015      1   10   NaN 2015-01-10
10    2015      1   11   NaN 2015-01-11
11    2015      1   12   NaN 2015-01-12
12    2015      1   13   NaN 2015-01-13
13    2015      1   14   NaN 2015-01-14
14    2015      1   15   NaN 2015-01-15
15    2015      1   16   NaN 2015-01-16
16    2015      1   17   NaN 2015-01-17
17    2015      1   18   NaN 2015-01-18
18    2015      1   19   NaN 2015-01-19
19    2015      1   20   NaN 2015-01-20
20    2015      1   21   NaN 2015-01-21
21    2015      1   22   NaN 2015-01-22
22    2015      1   23   NaN 2015-01-23
23    2015      1   24   NaN 2015-01-24
24    2015      1   25   NaN 2015-01-25
25    2015      1   26   NaN 2015-01-26
26    2015      1   27   NaN 2015-01-27
27    2015      1   28   NaN 2015-01-28
28    2015      1   29   NaN 2015-01-29
29    2015      1   30   NaN 2015-01-30
...    ...    ...  ...   ...        ...
1085  2017     12    1   NaN 2017-12-01
1086  2017     12    2   NaN 2017-12-02
1087  2017     12    3   NaN 2017-12-03
1088  2017     12    4   NaN 2017-12-04
1089  2017     12    5   NaN 2017-12-05
1090  2017     12    6   NaN 2017-12-06
1091  2017     12    7   NaN 2017-12-07
1092  2017     12    8   NaN 2017-12-08
1093  2017     12    9   NaN 2017-12-09
1094  2017     12   10   NaN 2017-12-10
1095  2017     12   11   NaN 2017-12-11
1096  2017     12   12   NaN 2017-12-12
1097  2017     12   13   NaN 2017-12-13
1098  2017     12   14   NaN 2017-12-14
1099  2017     12   15   NaN 2017-12-15
1100  2017     12   16   NaN 2017-12-16
1101  2017     12   17   NaN 2017-12-17
1102  2017     12   18   NaN 2017-12-18
1103  2017     12   19   NaN 2017-12-19
1104  2017     12   20   NaN 2017-12-20
1105  2017     12   21   NaN 2017-12-21
1106  2017     12   22   NaN 2017-12-22
1107  2017     12   23   NaN 2017-12-23
1108  2017     12   24   NaN 2017-12-24
1109  2017     12   25   NaN 2017-12-25
1110  2017     12   26   NaN 2017-12-26
1111  2017     12   27   NaN 2017-12-27
1112  2017     12   28   NaN 2017-12-28
1113  2017     12   29   NaN 2017-12-29
1114  2017     12   30   NaN 2017-12-30

[1095 rows x 5 columns]

In [16]:
tm_p = tm.set_index('date', inplace=True)

In [17]:
tm.columns

Index(['year', 'month', 'day', 'value'], dtype='object')

In [18]:
tm

            year  month  day value
date
2015-01-01  2015      1    1   NaN
2015-01-02  2015      1    2   NaN
2015-01-03  2015      1    3   NaN
2015-01-04  2015      1    4   NaN
2015-01-05  2015      1    5   NaN
2015-01-06  2015      1    6   NaN
2015-01-07  2015      1    7   NaN
2015-01-08  2015      1    8   NaN
2015-01-09  2015      1    9   NaN
2015-01-10  2015      1   10   NaN
2015-01-11  2015      1   11   NaN
2015-01-12  2015      1   12   NaN
2015-01-13  2015      1   13   NaN
2015-01-14  2015      1   14   NaN
2015-01-15  2015      1   15   NaN
2015-01-16  2015      1   16   NaN
2015-01-17  2015      1   17   NaN
2015-01-18  2015      1   18   NaN
2015-01-19  2015      1   19   NaN
2015-01-20  2015      1   20   NaN
2015-01-21  2015      1   21   NaN
2015-01-22  2015      1   22   NaN
2015-01-23  2015      1   23   NaN
2015-01-24  2015      1   24   NaN
2015-01-25  2015      1   25   NaN
2015-01-26  2015      1   26   NaN
2015-01-27  2015      1   27   NaN
2015-01-28  2015      1   28   NaN
2015-01-29  2015      1   29   NaN
2015-01-30  2015      1   30   NaN
...          ...    ...  ...   ...
2017-12-01  2017     12    1   NaN
2017-12-02  2017     12    2   NaN
2017-12-03  2017     12    3   NaN
2017-12-04  2017     12    4   NaN
2017-12-05  2017     12    5   NaN
2017-12-06  2017     12    6   NaN
2017-12-07  2017     12    7   NaN
2017-12-08  2017     12    8   NaN
2017-12-09  2017     12    9   NaN
2017-12-10  2017     12   10   NaN
2017-12-11  2017     12   11   NaN
2017-12-12  2017     12   12   NaN
2017-12-13  2017     12   13   NaN
2017-12-14  2017     12   14   NaN
2017-12-15  2017     12   15   NaN
2017-12-16  2017     12   16   NaN
2017-12-17  2017     12   17   NaN
2017-12-18  2017     12   18   NaN
2017-12-19  2017     12   19   NaN
2017-12-20  2017     12   20   NaN
2017-12-21  2017     12   21   NaN
2017-12-22  2017     12   22   NaN
2017-12-23  2017     12   23   NaN
2017-12-24  2017     12   24   NaN
2017-12-25  2017     12   25   NaN
2017-12-26  2017     12   26   NaN
2017-12-27  2017     12   27   NaN
2017-12-28  2017     12   28   NaN
2017-12-29  2017     12   29   NaN
2017-12-30  2017     12   30   NaN

[1095 rows x 4 columns]

In [19]:
#tm['2016'].value
tm= pd.Series(tm.value).convert_objects(convert_numeric=True)

/Users/gabriela/anaconda/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [ ]:
tm['2016-01-01':'2017-05-31']